### ISSUE TITLE
Who benefits from this?

### ISSUE THREAD

**Issue by marcanw** [distriqt/ANE-HuaweiMobileServices#1]
Can I use this Ane?
Which of your ANE can use this?
What's the benefit of it?
Thank you for your infos.

**Comment by marchbold** [comment]
This repository will form dependencies much like the [GooglePlayServices](https://github.com/distriqt/ANE-GooglePlayServices) repository for Google services.

We are currently beta testing AppGallery integration into the [InAppBilling](https://airnativeextensions.com/extension/com.distriqt.InAppBilling) extension and will be integrating Huawei Game Services into [GameServices](https://airnativeextensions.com/extension/com.distriqt.GameServices) extension next.

If you have any requests, contact our team at airnativeextensions@distriqt.com

**Comment by Marcophono2** [comment]
That is wonderful!
