### ISSUE TITLE
Google Play Rejection Notification HUAWEI SDK

### ISSUE THREAD

**Issue by apofis1969** [distriqt/ANE-HuaweiMobileServices#4]
HI, I got this email from Google Play.

Issue with your app
--
Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Huawei Mobile Services SDK which contains code to download or install applications from unknown sources outside of Google Play.After 120 days, new app releases containing this non-compliant version of this SDK will be rejected. This SDK version violates Device & Network Abuse policy.Given the nature of the SDK, we request that you remove it from the version of your app submitted to the Play Store.

Issue with your app 
Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Huawei Mobile Services SDK which contains code to download or install applications from unknown sources outside of Google Play.

After 120 days, new app releases containing this non-compliant version of this SDK will be rejected. This SDK version violates [Device & Network Abuse](https://notifications.google.com/g/p/AD-FnEzUUIVQ9MXuzwUdxT7vOOXs05xfcx5AuhJwWhZnb7Rf0u1Qmf1BDT5v2g8CxlxYTfl3JLgbsD8bGiiZwQC95it207N_j_xhUGOZ3x6Tjytt_axPPsWQV9Z-3CMT7W1CYegkHio_nUE) policy.

But I have no HUAWEI SDK. Look at the screenshot.
Is this an error of Google Play or is there somewhere a HUAWEI SDK in the ANEs I am using?

<img width="345" alt="Screenshot 2022-03-18 at 10 45 14" src="https://user-images.githubusercontent.com/25087613/159014697-24dc5ea7-66c2-45ab-b491-b7f427f74d08.png">

**Comment by marchbold** [comment]
The only extensions that we package the HMS into are the extensions in this repository, which aren't in your list. 

OneSignal may have some classes that use these services if available but I don't believe they include them in their SDK. 

Can you get any clarification from them on this issue?

**Comment by apofis1969** [comment]
Hi, yes. I will get in contact with them. This seems to be very strange

**Comment by marchbold** [comment]
Yeah definitely an odd one, I haven't had anyone else get picked up for this .

**Comment by apofis1969** [comment]
hi, they still complain. Look here. Now I sent a build with all the new ANEs and they still complain.
############
Hi developers

Thank you for your reply.

We found that you have resubmitted the app MyApp (air.com.xxx.xxx), however, the violation issue still exists. 

As we mentioned previously, during review, we found that your app causes users to download or install apps from unknown sources outside of Google Play, which is not compliant with our Device and Network Abuse policy.

You can read through the [Device & Network Abuse ](https://support.google.com/googleplay/android-developer/answer/9888379)policy page for more details and examples of common violations.

For example, your app (Track Internal Testing Version: 3000113) is using Huawei Mobile Services SDK or library, which causes users to download or install applications from unknown sources outside of Google Play.

Please note that all active APKs (including Alpha, Beta and Internal Testing track etc.,) should be compliant with our policy. Please submit the updated app and be sure to increment the APK version number and deactivate the non-compliant APK.

Thanks for working with us to fix the policy issue and for your continued support of Google Play.
############
see the screenshot of the ANEs. What the hell is going on at Google. They want to remove the app on Google Play.
The internal testing version never went online. The recent build is 3.0.270

<img width="384" alt="Screenshot 2022-03-28 at 09 57 34" src="https://user-images.githubusercontent.com/25087613/160402765-5c72443d-eddf-4127-baf1-d17617edcb9c.png">

**Comment by apofis1969** [comment]
Hi, may it be, that these badges of the push notifications create the problem? As I know Google Play does not accept Huawei anymore.
com.huawei.android.launcher.permission.CHANGE_BADGE, 
com.huawei.android.launcher.permission.READ_SETTINGS, 
com.huawei.android.launcher.permission.WRITE_SETTINGS,

**Comment by marchbold** [comment]
Can you post your manifest? You haven't added the `android.permission.REQUEST_INSTALL_PACKAGES` permission or something like that have you? 

You can try removing those huawei permissions but I can't see how they would cause this as they are just related to changing the notification badge number on huawei devices. 

Are you downloading any content from anywhere that could be misinterpreted as an application?

**Comment by apofis1969** [comment]
HI,

I do not use android.permission.REQUEST_INSTALL_PACKAGES. Please see the manifest attached.
The app connects to the database server and to the streaming server. All via https and rtmp
There are 3 XML files, which are used and located on the database server. But they just deliver variables and no content. They are used to display the correct Terms of Use and Privacy Policy languages, update informations and FAQs in the user language. All sheets are called via https and NativeWebView ANE. Also the build they are complaining about - internal testing - even did not have this features. They complain about Huawei SDK and that the app may be installed outside of Google Play.

[android_manifest.txt](https://github.com/distriqt/ANE-HuaweiMobileServices/files/8371210/android_manifest.txt)

**Comment by marchbold** [comment]
Bit of a loss then, my only guess is that the OneSignal SDK includes some of the HMS services but that surprises me.

**Comment by apofis1969** [comment]
And what can I do? Remove push notifications? This is impossible

this is the newest reply and there is no chat can help.
##################
Thank you for your reply.

As mentioned previously, we found that Track Internal Testing Version: 3000113  is using Huawei Mobile Services SDK or library, and still exists in this submission.

Please confirm if you have used [managed publishing](https://support.google.com/googleplay/android-developer/answer/9859654?hl=en&ref_topic=7072031).

Please contact [Play Console Help Center](https://support.google.com/googleplay/android-developer/?hl=en#topic=) if you need assistance on deactivating specific apk.
#####################

**Comment by marchbold** [comment]
Maybe just try a build with the base variant of the push notifications extension and upload that to the console. It only includes fcm on android so shouldn't have any huawei references at all and will confirm if onesignal is the cause.

**Comment by apofis1969** [comment]
Do you mean not to take the library of one signal? How is then the manifest? Stays the same as well as the code?

**Comment by marchbold** [comment]
Ah yeah, you'll have to change the manifest but that should be the only change you'll need to make.

**Comment by apofis1969** [comment]
But how do I have to change the manifest. Which manifest do I have to add? I tried with the manifest I have now and the app crashes. Is all adapted for ONESIGNAL. The server sends over the rest api from onesignal the push to the receiver, if the base station realises an activity. Please help me through this. Thank you
In the meanwhile I removed all deprecated code in the manifest and also the HUAWEI Badges permissions. Maybe they saw the deprecated code as well. Checking the app with policy violation does not appear anything.

**Comment by marchbold** [comment]
Right, so just to confirm what you have said, removing entries from the manifest resolved the issue? 

I highly recommend using apm going forward as this would keep a clean manifest automatically for you.

**Comment by apofis1969** [comment]
Hi,
I do not know until now. I created an aab build and tested yesterday. Fact is, that the Huawei permissions are deleted and the deprecated code which I removed with <!~~ —> has been deleted as well. I will send this build today with managed publishing. And sent also all new builds to test to the internal testing. So the build they complained is deprecated. But I can not delete the build. Need to get in contact with Google Play support again to remove this build or to let them confirm that there is no violation anymore.
Hopefully the problem is resolved now. The APM feature do I have to figure out..

**Comment by marchbold** [comment]
Okay, let me know how it goes.

**Comment by Xuejiao-Shi** [comment]
Huawei has provided new version for this issue. You could obtain the latest SDK version from the official website.

[Version Change History](https://developer.huawei.com/consumer/en/doc/development/hmscore-common-Guides/hmssdk-kit-0000001050042513#section17370146238)

**Comment by marchbold** [comment]
We will add an update to HMS to our schedule.

**Comment by marchbold** [comment]
HMS has been updated.
